//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.11 at 03:54:26 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.geekbrains.ru/spring/ws/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.geekbrains.spring2.soap.products;
